name: Sync admin branch with main

on:
  push:
    branches:
      - main

jobs:
  sync-admin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Push main to admin branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.Ivy_league_PAT }}@github.com/${{ github.repository }}
          git push origin main:admin --force

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm